[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "HydroInverseML"
version = "0.1.0"
dependencies = [
  "torch>=2.0.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0"
]